project:
  type: website

website:
  site-url: https://marticatala.quarto.pub/myprofile/
  title: "omopverse"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  repo-url: https://github.com/catalamarti/website-test
  repo-actions: [issue]
  page-footer: 
    left: "Copyright 2024, Oxinfer"
    right: 
      - text: Github
        href: https://github.com/oxford-pharmacoepi
        icon: github
      - text: Twitter
        href: https://x.com/CatalaMarti
        icon: twitter
      - text: Youtube Channel
        href: https://www.youtube.com/@oxinfer
        icon: youtube
      
  navbar:
    title: "omopverse"
    search: false
    left: 
      - text: Home
        href: index.qmd
        icon: house
      - text: Packages
        icon: boxes
        href: packages/index.qmd
    tools: 
      - text: Github
        href: https://github.com/oxford-pharmacoepi
        icon: github
      - text: Youtube Channel
        href: https://www.youtube.com/@oxinfer
        icon: youtube
      - text: Twitter
        icon: twitter
        href: https://x.com/CatalaMarti
      
format:
  html:
    toc: true
    fontcolor: black
    linkcolor: green
    backgroundcolor: white #'#fffdd0'
    mainfont: ui-rounded
    monofont: cursive
    #fontsize: 10pt
    #max-width: 10px
    #linestretch: 1.5em
    theme: [cosmo, styles.scss]
  